// IHSA COR 2020 (Ontario / National COR 2020) audit crosswalk.
//
// The 161 scored questions of the IHSA COR 2020 Audit Tool (v2.0, October 2022),
// paraphrased (not the CP's verbatim copyrighted text), each mapped to the
// evidence in this app's COR document set, the verification technique the tool
// assigns (documentation, interview, or observation), and where it lives. COR
// 2020 is a national standard (CFCSA) administered by IHSA in Ontario, with a
// finer 14-element structure than the Alberta instruments; element and question
// numbers are IHSA's. Every element repeats a "documents and records maintained
// per 1.2 Document and Record Control" question, mapped to shared document-control
// evidence. A company runs one program, so the evidence library is shared.

import type { CorCrosswalkQuestion } from "@/lib/cor-crosswalk";

export const IHSA_CROSSWALK: CorCrosswalkQuestion[] = [
  // Element 1
  { id: "1.1.1", element: 1, method: "documentation", question: "Policy commits senior management to set and review OHS objectives and continual improvement", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.2", element: 1, method: "documentation", question: "Policy commits management to a safe and healthy work environment", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.3", element: 1, method: "documentation", question: "Policy commits to comply with OHS legal and other requirements", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.4", element: 1, method: "documentation", question: "Policy commits to consultation and cooperation with workers", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.5", element: 1, method: "documentation", question: "Policy references a program addressing responsibilities of workplace parties", evidence: "Health and Safety Policy, Roles and Responsibilities", location: "Policies" },
  { id: "1.1.6", element: 1, method: "documentation", question: "Policy recognizes the worker's right to a safe and healthy workplace", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.7", element: 1, method: "documentation", question: "Policy signed by the president, CEO, or local senior management", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.8", element: 1, method: "documentation", question: "Policy is current", evidence: "Health and Safety Policy", location: "Policies" },
  { id: "1.1.9", element: 1, method: "observation", question: "Policy visibly posted in the workplace", evidence: "Health and Safety Policy (posted)", location: "Policies" },
  { id: "1.1.10", element: 1, method: "documentation", question: "Policy reviewed at least annually", evidence: "Annual Program Review, Health and Safety Policy", location: "Forms" },
  { id: "1.1.11", element: 1, method: "documentation", question: "Policy communicated to and understood by employees", evidence: "New Worker Orientation, Safety Meetings", location: "Safety Manual" },
  { id: "1.2.1", element: 1, method: "documentation", question: "Written procedure for documentation, document control, and record control", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 2
  { id: "2.1", element: 2, method: "documentation", question: "Documented hazard assessment policy, current and signed by senior management", evidence: "Hazard Assessment policy", location: "Policies" },
  { id: "2.2", element: 2, method: "documentation", question: "Written procedure for hazard assessment, analysis, and control", evidence: "Formal and Field-Level Hazard Assessment procedure", location: "Safety Manual" },
  { id: "2.3", element: 2, method: "documentation", question: "Hazard assessments conducted, documented, and approved for all operations", evidence: "Formal Hazard Assessment", location: "Forms" },
  { id: "2.4", element: 2, method: "documentation", question: "Hazard assessments updated per the procedure", evidence: "Formal Hazard Assessment (dated reviews)", location: "Forms" },
  { id: "2.5", element: 2, method: "documentation", question: "Appropriate workplace parties involved in hazard assessment", evidence: "Formal Hazard Assessment (signatures)", location: "Forms" },
  { id: "2.6", element: 2, method: "documentation", question: "Workplace and job-specific hazards clearly identified", evidence: "Formal Hazard Assessment", location: "Forms" },
  { id: "2.7", element: 2, method: "documentation", question: "Risks prioritized before identifying controls", evidence: "Formal Hazard Assessment (risk matrix)", location: "Forms" },
  { id: "2.8", element: 2, method: "documentation", question: "Residual risks prioritized after identifying controls", evidence: "Formal Hazard Assessment (residual risk)", location: "Forms" },
  { id: "2.9", element: 2, method: "documentation", question: "List of critical tasks identified by a company risk rating", evidence: "Position and Task Inventory, Orientation 06 High Risk Hazards", location: "Forms" },
  { id: "2.10", element: 2, method: "documentation", question: "Documented controls referenced in the hazard assessments", evidence: "Formal Hazard Assessment (controls)", location: "Forms" },
  { id: "2.11", element: 2, method: "documentation", question: "Control measures made available and employees informed", evidence: "Safe work procedures, Safety Meetings", location: "Safety Manual" },
  { id: "2.12", element: 2, method: "observation", question: "Documented controls implemented for identified hazards", evidence: "Hazard controls in use, Equipment module", location: "App" },
  { id: "2.13", element: 2, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 3
  { id: "3.1", element: 3, method: "documentation", question: "Documented controls policy, current and signed by senior management", evidence: "Hazard Control policy", location: "Policies" },
  { id: "3.2", element: 3, method: "documentation", question: "Written procedure for controls including roles, approval, and hierarchy", evidence: "Hazard Control procedure", location: "Safety Manual" },
  { id: "3.3", element: 3, method: "documentation", question: "Controls documented and approved per the procedure", evidence: "Safe Work Procedure Template", location: "Forms" },
  { id: "3.4", element: 3, method: "documentation", question: "Documented controls reflect the organization's activities", evidence: "Safe work procedures", location: "Safety Manual" },
  { id: "3.5", element: 3, method: "documentation", question: "Controls developed following the hierarchy of controls", evidence: "Safe Work Procedure Template (hierarchy)", location: "Forms" },
  { id: "3.6", element: 3, method: "documentation", question: "Controls communicated to affected workplace parties", evidence: "Safety Meetings, safe work procedures", location: "Safety Manual" },
  { id: "3.7", element: 3, method: "documentation", question: "Controls understood by workers", evidence: "Safe work procedures", location: "Safety Manual" },
  { id: "3.8", element: 3, method: "observation", question: "Controls readily available at the point of use", evidence: "Safe work procedures on the worker app", location: "App" },
  { id: "3.9", element: 3, method: "observation", question: "Control requirements followed by all workplace parties", evidence: "Safe work procedures in use", location: "App" },
  { id: "3.10", element: 3, method: "documentation", question: "Management and workers participate in developing and reviewing controls", evidence: "Hazard assessments (signatures), Safety Meetings", location: "Forms" },
  { id: "3.11", element: 3, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 4
  { id: "4.1", element: 4, method: "documentation", question: "Documented procurement and contractor management policy, signed and dated", evidence: "Other Parties policy", location: "Policies" },
  { id: "4.2", element: 4, method: "documentation", question: "Written procedure for procurement and contractor management", evidence: "Contractor Management procedure", location: "Safety Manual" },
  { id: "4.3", element: 4, method: "documentation", question: "OHS criteria followed for selecting contractors and service providers", evidence: "Contractor Pre-Qualification", location: "Forms" },
  { id: "4.4", element: 4, method: "documentation", question: "Contractors and service providers monitored per the procedure", evidence: "Contractor Orientation (monitoring)", location: "Forms" },
  { id: "4.5", element: 4, method: "documentation", question: "Contractors and service providers evaluated per the procedure", evidence: "Contractor Pre-Qualification (evaluation)", location: "Forms" },
  { id: "4.6", element: 4, method: "documentation", question: "Relevant parties informed when changes occur", evidence: "Other Parties policy, Safety Meetings", location: "Policies" },
  { id: "4.7", element: 4, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 5
  { id: "5.1", element: 5, method: "documentation", question: "Documented company rules policy, current and signed by senior management", evidence: "Company Rules policy", location: "Policies" },
  { id: "5.2", element: 5, method: "documentation", question: "Written procedure for company rules", evidence: "Company Rules procedure", location: "Safety Manual" },
  { id: "5.3", element: 5, method: "documentation", question: "Company rules clearly stated in writing", evidence: "Company Safety Rules", location: "Policies" },
  { id: "5.4", element: 5, method: "observation", question: "Rules visibly posted or provided to each employee", evidence: "Company Safety Rules (posted), Orientation", location: "Policies" },
  { id: "5.5", element: 5, method: "interview", question: "Workers understand the company rules", evidence: "Orientation, Safety Meetings", location: "Safety Manual" },
  { id: "5.6", element: 5, method: "documentation", question: "Company rules applied and enforced consistently", evidence: "Safety Enforcement and Discipline policy", location: "Policies" },
  { id: "5.7", element: 5, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 6
  { id: "6.1", element: 6, method: "documentation", question: "Documented PPE policy, current and signed by senior management", evidence: "PPE Policy", location: "Policies" },
  { id: "6.2", element: 6, method: "documentation", question: "Written procedure for PPE", evidence: "PPE procedure", location: "Safety Manual" },
  { id: "6.3", element: 6, method: "documentation", question: "Required PPE documented for all activities", evidence: "Formal Hazard Assessment (PPE), PPE Policy", location: "Forms" },
  { id: "6.4", element: 6, method: "documentation", question: "PPE selected per the procedure", evidence: "PPE Policy", location: "Policies" },
  { id: "6.5", element: 6, method: "documentation", question: "Written rules for the fitting, care, and use of PPE", evidence: "PPE Policy", location: "Policies" },
  { id: "6.6", element: 6, method: "documentation", question: "Workers made aware of PPE fitting, care, and use", evidence: "Orientation, PPE Policy", location: "Safety Manual" },
  { id: "6.7", element: 6, method: "documentation", question: "Adequate PPE provided and available for activities", evidence: "PPE Policy", location: "Policies" },
  { id: "6.8", element: 6, method: "documentation", question: "PPE inspected per manufacturer and legislative requirements", evidence: "Worksite Inspection (PPE checks)", location: "Forms" },
  { id: "6.9", element: 6, method: "observation", question: "Management, workers, and subcontractors use required PPE", evidence: "PPE in use on site", location: "App" },
  { id: "6.10", element: 6, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 7
  { id: "7.1", element: 7, method: "documentation", question: "Documented preventative maintenance policy, current and signed", evidence: "Preventative Maintenance policy", location: "Policies" },
  { id: "7.2", element: 7, method: "documentation", question: "Written procedure for preventative maintenance", evidence: "Preventative Maintenance procedure", location: "Safety Manual" },
  { id: "7.3", element: 7, method: "documentation", question: "Inventory of items to be maintained", evidence: "Equipment module (inventory)", location: "App" },
  { id: "7.4", element: 7, method: "documentation", question: "Schedules meet manufacturer and legislative requirements", evidence: "Equipment module (service schedules)", location: "App" },
  { id: "7.5", element: 7, method: "documentation", question: "Preventative maintenance performed as planned", evidence: "Equipment module maintenance records", location: "App" },
  { id: "7.6", element: 7, method: "documentation", question: "Records include corrective action taken", evidence: "Equipment module (service records)", location: "App" },
  { id: "7.7", element: 7, method: "documentation", question: "Competent worker performs inspection and maintenance", evidence: "Preventative Maintenance procedure", location: "Safety Manual" },
  { id: "7.8", element: 7, method: "documentation", question: "Defective vehicles, tools, and equipment removed from service", evidence: "Equipment module (out of service)", location: "App" },
  { id: "7.9", element: 7, method: "documentation", question: "Items overdue for maintenance removed from service", evidence: "Equipment module (out of service)", location: "App" },
  { id: "7.10", element: 7, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 8
  { id: "8.1.1", element: 8, method: "documentation", question: "Documented training policy, current and signed by senior management", evidence: "Training policy", location: "Policies" },
  { id: "8.1.2", element: 8, method: "documentation", question: "Written procedure for training", evidence: "Training procedure", location: "Safety Manual" },
  { id: "8.1.3", element: 8, method: "documentation", question: "Training accommodates differing levels of responsibility", evidence: "Training Matrix", location: "Forms" },
  { id: "8.1.4", element: 8, method: "documentation", question: "Competencies identified for each task and role", evidence: "Worker Competency Assessment, Position and Task Inventory", location: "Forms" },
  { id: "8.1.5", element: 8, method: "documentation", question: "Training needs analysis conducted per the procedure", evidence: "Training Matrix", location: "Forms" },
  { id: "8.1.6", element: 8, method: "documentation", question: "Employees received legislation-required training", evidence: "Training and Certification Log, Certifications", location: "App" },
  { id: "8.1.7", element: 8, method: "documentation", question: "Employees received training per the procedure", evidence: "Training and Certification Log", location: "App" },
  { id: "8.1.8", element: 8, method: "documentation", question: "Training provided before the worker performs the task", evidence: "Worker Competency Assessment", location: "Forms" },
  { id: "8.1.9", element: 8, method: "documentation", question: "Orientation mandatory for all workers", evidence: "New Worker Orientation policy", location: "Policies" },
  { id: "8.1.10", element: 8, method: "documentation", question: "Orientation training provided per the procedure", evidence: "New Worker Orientation Checklist", location: "Forms" },
  { id: "8.1.11", element: 8, method: "documentation", question: "In-house training delivered by a qualified, competent person", evidence: "Training and Certification Log", location: "App" },
  { id: "8.1.12", element: 8, method: "documentation", question: "Learning evaluated per the procedure", evidence: "Worker Competency Assessment", location: "Forms" },
  { id: "8.1.13", element: 8, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  { id: "8.2.1", element: 8, method: "documentation", question: "Documented communication policy, current and signed", evidence: "Communication policy", location: "Policies" },
  { id: "8.2.2", element: 8, method: "documentation", question: "Written procedure for communication", evidence: "Communication procedure", location: "Safety Manual" },
  { id: "8.2.3", element: 8, method: "documentation", question: "Scheduled company-wide OHS meetings held", evidence: "Safety Meeting Agenda and Minutes", location: "Forms" },
  { id: "8.2.4", element: 8, method: "documentation", question: "Senior management attends organization-wide OHS meetings", evidence: "Safety Meeting Agenda and Minutes (attendance)", location: "Forms" },
  { id: "8.2.5", element: 8, method: "documentation", question: "Two-way communication occurs during meetings", evidence: "Safety Meetings, Health and Safety Recommendation", location: "Forms" },
  { id: "8.2.6", element: 8, method: "documentation", question: "Tailgate or toolbox talks held as scheduled", evidence: "Toolbox Talk and Tailgate Meeting", location: "Forms" },
  { id: "8.2.7", element: 8, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 9
  { id: "9.1", element: 9, method: "documentation", question: "Documented workplace inspections policy, current and signed", evidence: "Inspections policy", location: "Policies" },
  { id: "9.2", element: 9, method: "documentation", question: "Written procedure for workplace inspections", evidence: "Inspections procedure", location: "Safety Manual" },
  { id: "9.3", element: 9, method: "documentation", question: "Inspections conducted using the required forms and checklists", evidence: "Worksite and Shop Inspection", location: "Forms" },
  { id: "9.4", element: 9, method: "documentation", question: "Inspection frequencies adhered to", evidence: "Inspection submissions", location: "App" },
  { id: "9.5", element: 9, method: "documentation", question: "Assigned personnel perform inspections as required", evidence: "Inspections policy", location: "Policies" },
  { id: "9.6", element: 9, method: "documentation", question: "Pre-use inspections performed per the procedure", evidence: "Pre-Trip Inspection, Pre-Use Inspection", location: "Forms" },
  { id: "9.7", element: 9, method: "documentation", question: "Inspections meet legislative and manufacturer requirements", evidence: "Inspection forms", location: "Forms" },
  { id: "9.8", element: 9, method: "documentation", question: "Workers involved in the inspection process", evidence: "Inspection records", location: "App" },
  { id: "9.9", element: 9, method: "documentation", question: "Identified deficiencies corrected in a timely manner", evidence: "Worksite Inspection (corrective actions), Workflow Station", location: "App" },
  { id: "9.10", element: 9, method: "documentation", question: "Inspection results communicated to senior management", evidence: "Inspection records, Annual Program Review", location: "App" },
  { id: "9.11", element: 9, method: "documentation", question: "Inspection reports communicated to relevant parties", evidence: "Safety Meetings, inspection records", location: "Forms" },
  { id: "9.12", element: 9, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 10
  { id: "10.1", element: 10, method: "documentation", question: "Documented investigations and reporting policy, current and signed", evidence: "Incident Investigation policy", location: "Policies" },
  { id: "10.2", element: 10, method: "documentation", question: "Written investigation and reporting procedure meeting legislation", evidence: "Incident Investigation procedure", location: "Safety Manual" },
  { id: "10.3", element: 10, method: "documentation", question: "Records show the investigation and reporting procedure is followed", evidence: "Incident Report and Investigation", location: "Forms" },
  { id: "10.4", element: 10, method: "documentation", question: "Workplace parties aware of reporting procedures", evidence: "Orientation 08 Incident Reporting", location: "Safety Manual" },
  { id: "10.5", element: 10, method: "documentation", question: "Required personnel trained in reporting and investigation", evidence: "Incident Investigation Training certificate (Certification Types)", location: "App" },
  { id: "10.6", element: 10, method: "documentation", question: "Appropriate personnel involved in investigations", evidence: "Incident Report and Investigation", location: "Forms" },
  { id: "10.7", element: 10, method: "documentation", question: "Corrective and preventive actions identified and addressed", evidence: "Incident Report form (corrective actions)", location: "Forms" },
  { id: "10.8", element: 10, method: "documentation", question: "Corrective and preventive actions implemented per the procedure", evidence: "Incident Report form, Workflow Station", location: "App" },
  { id: "10.9", element: 10, method: "documentation", question: "Corrective and preventive actions communicated to workers", evidence: "Safety Meetings", location: "Forms" },
  { id: "10.10", element: 10, method: "documentation", question: "Effectiveness of corrective and preventive actions measured", evidence: "Incident records, Annual Program Review", location: "App" },
  { id: "10.11", element: 10, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 11
  { id: "11.1", element: 11, method: "documentation", question: "Documented emergency preparedness policy, current and signed", evidence: "Emergency Preparedness policy", location: "Policies" },
  { id: "11.2", element: 11, method: "documentation", question: "Written procedure for emergency preparedness", evidence: "Emergency Response Plan procedure", location: "Safety Manual" },
  { id: "11.3", element: 11, method: "documentation", question: "Emergency plans include appropriate responses to identified hazards", evidence: "Emergency Response Plan", location: "Safety Manual" },
  { id: "11.4", element: 11, method: "documentation", question: "Emergency response plans reviewed per the procedure", evidence: "Emergency Response Plan (review)", location: "Safety Manual" },
  { id: "11.5", element: 11, method: "documentation", question: "Emergency response resources identified and available", evidence: "Emergency Response Plan", location: "Safety Manual" },
  { id: "11.6", element: 11, method: "documentation", question: "Plans include periodic inspection of first aid facilities", evidence: "Emergency Response Plan, Worksite Inspection (first aid)", location: "Forms" },
  { id: "11.7", element: 11, method: "documentation", question: "Plans define roles and include emergency procedure training", evidence: "Orientation 04 Emergency Response", location: "Safety Manual" },
  { id: "11.8", element: 11, method: "documentation", question: "Emergency response information communicated to relevant parties", evidence: "Orientation 04 Emergency Response, Safety Meetings", location: "Safety Manual" },
  { id: "11.9", element: 11, method: "documentation", question: "Emergency communication system in place to alert parties", evidence: "Emergency Response Plan", location: "Safety Manual" },
  { id: "11.10", element: 11, method: "documentation", question: "Plan tested for deficiencies with corrective action taken", evidence: "Emergency Drill Record", location: "Forms" },
  { id: "11.11", element: 11, method: "documentation", question: "Appropriate fire extinguishers at marked locations", evidence: "Worksite Inspection (fire extinguisher checks)", location: "Forms" },
  { id: "11.12", element: 11, method: "documentation", question: "Workers required to use fire extinguishers are trained", evidence: "Training and Certification Log", location: "App" },
  { id: "11.13", element: 11, method: "documentation", question: "Fire extinguishers regularly inspected and maintained", evidence: "Worksite Inspection (fire extinguisher checks)", location: "Forms" },
  { id: "11.14", element: 11, method: "documentation", question: "Provision for transporting an injured worker to medical care", evidence: "Emergency Response Plan", location: "Safety Manual" },
  { id: "11.15", element: 11, method: "observation", question: "Required first aid stations, facilities, and supplies available", evidence: "Worksite Inspection (first aid checks)", location: "Forms" },
  { id: "11.16", element: 11, method: "documentation", question: "Qualified first aiders available on every shift", evidence: "Emergency Contact List and First Aiders", location: "Forms" },
  { id: "11.17", element: 11, method: "documentation", question: "Other emergency response equipment inspected and maintained", evidence: "Worksite Inspection, Equipment module", location: "App" },
  { id: "11.18", element: 11, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 12
  { id: "12.1", element: 12, method: "documentation", question: "Documented statistics and records policy, current and signed", evidence: "Statistics and Records policy", location: "Policies" },
  { id: "12.2", element: 12, method: "documentation", question: "Written procedure for statistics and records", evidence: "Statistics and Records procedure", location: "Safety Manual" },
  { id: "12.3", element: 12, method: "documentation", question: "Health and safety summaries developed and maintained", evidence: "Annual Program Review, Analytics module", location: "App" },
  { id: "12.4", element: 12, method: "documentation", question: "OHS performance measured at the specified frequency", evidence: "Analytics module", location: "App" },
  { id: "12.5", element: 12, method: "documentation", question: "Performance compared with past performance", evidence: "Annual Program Review, Analytics module", location: "App" },
  { id: "12.6", element: 12, method: "documentation", question: "Statistics analyzed and trends identified", evidence: "Annual Program Review, Analytics module", location: "App" },
  { id: "12.7", element: 12, method: "documentation", question: "First aid treatment records analyzed", evidence: "Analytics module, first aid records", location: "App" },
  { id: "12.8", element: 12, method: "documentation", question: "Results communicated to relevant workplace parties", evidence: "Safety Meetings, Annual Program Review", location: "Forms" },
  { id: "12.9", element: 12, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 13
  { id: "13.1", element: 13, method: "documentation", question: "Documented legislation and other requirements policy, current and signed", evidence: "Legislation policy", location: "Policies" },
  { id: "13.2", element: 13, method: "documentation", question: "Written procedure for legislation and other requirements", evidence: "Legislation procedure", location: "Safety Manual" },
  { id: "13.3", element: 13, method: "documentation", question: "Applicable legislation, standards, and requirements identified", evidence: "OHS Legislation Reference", location: "Policies" },
  { id: "13.4", element: 13, method: "documentation", question: "Compliance to current legislation evaluated per the procedure", evidence: "OHS Legislation Reference, Annual Program Review", location: "Policies" },
  { id: "13.5", element: 13, method: "observation", question: "Relevant legislation available or posted at each workplace", evidence: "OHS Act, Regulation, and Code in the Resource Library", location: "App" },
  { id: "13.6", element: 13, method: "observation", question: "Legislated posting requirements met", evidence: "Posted legislation and notices", location: "App" },
  { id: "13.7", element: 13, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  // Element 14
  { id: "14.1.1", element: 14, method: "documentation", question: "Documented senior management review policy, current and signed", evidence: "Management Review policy", location: "Policies" },
  { id: "14.1.2", element: 14, method: "documentation", question: "Written procedure for management review", evidence: "Management Review procedure", location: "Safety Manual" },
  { id: "14.1.3", element: 14, method: "documentation", question: "Review includes all inputs per the procedure", evidence: "Annual Program Review", location: "Forms" },
  { id: "14.1.4", element: 14, method: "documentation", question: "Measurable OHS objectives identified from the review", evidence: "Annual Program Review (objectives)", location: "Forms" },
  { id: "14.1.5", element: 14, method: "documentation", question: "OHS policies reviewed and updated", evidence: "Annual Program Review, Health and Safety Policy", location: "Forms" },
  { id: "14.1.6", element: 14, method: "documentation", question: "Action plan developed and resources identified for objectives", evidence: "Annual Program Review (action plan)", location: "Forms" },
  { id: "14.1.7", element: 14, method: "documentation", question: "Objectives and action plan communicated to all employees", evidence: "Safety Meetings, Annual Program Review", location: "Forms" },
  { id: "14.1.8", element: 14, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
  { id: "14.2.1", element: 14, method: "documentation", question: "Documented management of change policy, current and signed", evidence: "Management of Change policy", location: "Policies" },
  { id: "14.2.2", element: 14, method: "documentation", question: "Written procedure for management of change", evidence: "Management of Change procedure", location: "Safety Manual" },
  { id: "14.2.3", element: 14, method: "documentation", question: "Hazard assessment done for identified changes", evidence: "Management of Change, Field-Level Hazard Assessment", location: "Forms" },
  { id: "14.2.4", element: 14, method: "documentation", question: "Controls developed from the change hazard assessment", evidence: "Management of Change, Safe Work Procedure Template", location: "Forms" },
  { id: "14.2.5", element: 14, method: "documentation", question: "Changes communicated and training provided", evidence: "Management of Change, Safety Meetings", location: "Safety Manual" },
  { id: "14.2.6", element: 14, method: "documentation", question: "Documents and records maintained per the document and record control procedure", evidence: "Document and Record Control procedure, HSMS Administration", location: "Policies" },
];
